language: cpp
compiler: gcc
notifications:
  email: false
before_install:
  - sudo apt-get install build-essential git autoconf libssl-dev libprotobuf-dev protobuf-compiler libqt4-dev libqrencode-dev -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.55-all-dev
script: ./install.sh
